### ISSUE TITLE
Foreign key constraint violation on POST req

### ISSUE THREAD

**Issue by mcnaveen** [pevey/medusa-plugin-blog#1]
Update: Nah, I was wrong, First I created a category, then blog post. It's working now.

Looks like the plugin isn't performing the migration automatically. So I had to run `npx @medusajs/medusa-cli migrations run

Everything went well. But when I tried to create a new blog post. I came across a foreign key constraint violation. 

```
 driverError: error: insert or update on table "blog_post" violates foreign key constraint "FK_543439d139e604f9553a07dfa3f"
```

**Comment by pevey** [comment]
You may want to try `medusa migration revert`, which will drop all the blog tables, and then start fresh.  Running `medusa migrations run` again should give you a fresh playground to test with.

EDIT: Never mind, I see you updated your post.

**Comment by mcnaveen** [comment]
Cool. Btw, Any plans to add the frontend?

**Comment by pevey** [comment]
Yes, I plan to catch up with some of the new features and work on some admin plugins this weekend.
